version: '3.8'

networks:
    web_net:
        external: false

volumes:
    traefik-acme:
        name: traefik-acme

services:

    traefik:
        image: "traefik:v2.8"
        restart: always
        container_name: "traefik"
        command:
            - "--log.level=ERROR"
            - "--log.filepath=/log-file.log"
            - "--log.format=json"
            - "--accesslog=true"
            - "--accesslog.fields.names.StartUTC=drop"
            - "--accesslog.bufferingsize=250"
            - "--api=true"
            - "--ping=true"
            - "--api.insecure=true"
            #- "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--providers.docker.endpoint=unix:///var/run/docker.sock"
            - "--providers.docker.network=web_net"
            - "--entrypoints.http.address=:80"
            - "--entrypoints.https.address=:443"
            #- "--metrics.prometheus=true"
            #- "--entryPoints.metrics.address=:8082"
            #- "--metrics.prometheus.entryPoints=metrics"
            #- "--certificatesresolvers.myresolver.acme.tlschallenge=true"
            #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
            #- "--certificatesresolvers.myresolver.acme.email=postmaster@example.com"
            #- "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
            - "--providers.file.filename=/traefik/config.yml"
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - traefik-acme:/acme
          - ./traefik:/traefik:rw
        environment:
            - "TZ=Asia/Tehran"
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=web_net"
            - "traefik.http.routers.traefik.entrypoints=http"
            - "traefik.http.routers.traefik.rule=Host(`traefik.arye.ir`)"
            - "traefik.http.routers.traefik.middlewares=https-redirect"
            - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
            - "traefik.http.middlewares.web-auth.basicauth.users=arye:$$apr1$$9tK8pA6Q$$7Y88j7bJkBTgTrJjQN211."

            - "traefik.http.routers.traefik-secure.middlewares=web-auth"
            - "traefik.http.routers.traefik-secure.entrypoints=https"
            - "traefik.http.routers.traefik-secure.rule=Host(`traefik.arye.ir`)"
            - "traefik.http.routers.traefik-secure.tls=true" 
            - "traefik.http.routers.traefik-secure.tls.options=default"
            - "traefik.http.routers.traefik-secure.tls.certresolver=mycert"
            - "traefik.http.services.traefik.loadbalancer.server.port=8080"
        networks:
        - web_net
