global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:

  - job_name: 'prometheus'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'prometheus:9090'
  
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'grafana'
    scrape_interval: 30s
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'grafana:3000'



  - job_name: 'traefik'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'traefik:8082'
      #- targets: ['traefik:8080']
    